### ISSUE TITLE
vite-plugin-require-context doesn't work for images

### ISSUE THREAD

**Issue by ScubaDaniel** [originjs/vite-plugins#32]
I've tried both of the following with various levels of configuration and can't get it to work.

I've defined the `projectBasePath` to the root directory just above `src` and as `src` and neither work. I've tried defining the asset in `assetsInclude` and `build.rollupOptions.external` and nothing seems to change. Is this plugin for JS only?

```ts
// src/SISU/shared/utilities/images-helper.ts
export const images = require.context("@Product/images/", false, /^.+?\.png|jpg|svg|gif$/);
```

```ts
// src/SISU/shared/utilities/images-helper.ts
export const images = require.context("../../../Product/images/", false, /^.+?\.png|jpg|svg|gif$/);
```

Output:
```
[vite]: Rollup failed to resolve import "/src/Product/images/arrow_left.png" from "utilities/images-helper.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

Error: [vite]: Rollup failed to resolve import "/src/Product/images/arrow_left.png" from "utilities/images-helper.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

    at onRollupWarning (E:\root\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:41489:19)
    at onwarn (E:\root\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:41305:13)
    at Object.onwarn (E:\root\node_modules\rollup\dist\shared\rollup.js:23226:13)
    at ModuleLoader.handleResolveId (E:\root\node_modules\rollup\dist\shared\rollup.js:22510:26)
    at E:\root\node_modules\rollup\dist\shared\rollup.js:22471:26

TypeError: Cannot read properties of undefined (reading 'httpServer')
```

**Comment by PeterAlfredLee** [comment]
Hi @ScubaDaniel 
Thank you for your reporting.

This `require.context` plugin just transform the `require.context`syntax into `import`, not containing any loaders. Actually vite has integrated [asset loader](https://vitejs.dev/guide/assets.html) that can handle images - this loader will return the url of the image.

What are you expecting to get when you are importing an image? By default, vite will return the url of the image.

I made some tests with `require.context` and images, and they worked well. Maybe you can provide some more details?
``` javascript
// test.js
export const images = require.context('../assets', false, /^.+?\.png|jpg|svg|gif$/);
```
```javascript
// HelloWorld.vue
<script setup>
import image from '../assets/logo.png'
import * as test from './test'
const images = require.context('../assets', false, /^.+?\.png|jpg|svg|gif$/)
import {onMounted, ref} from 'vue'

defineProps({
  msg: String
})

const count = ref(0)

onMounted(() => {
  console.log(test);
  console.log(image);
  console.log(images);
})
</script>
```

**Comment by ScubaDaniel** [comment]
I just read some documentation on [Vite plugins](https://vitejs.dev/guide/using-plugins.html#adding-a-plugin). Should this be run before the Vite core plugins? I noticed I am getting a different error when using the following config:
```
plugins: [
  {
    ...ViteRequireContext(),
    enforce: "pre",
  },
]
```

Error:
```
[vite:require-context] Cannot read properties of undefined (reading '0')
file: E:/root/src/SISU/shared/utilities/images-helper.ts

TypeError: Cannot read properties of undefined (reading '0')

    at transformRequireContext (E:\root\node_modules\@originjs\vite-plugin-require-context\lib\index.js:106:22)
    at E:\root\node_modules\@originjs\vite-plugin-require-context\lib\index.js:58:114
    at Array.forEach (<anonymous>)
    at Object.transform (E:root\node_modules\@originjs\vite-plugin-require-context\lib\index.js:52:35)
    at E:\root\node_modules\rollup\dist\shared\rollup.js:22870:37

TypeError: Cannot read properties of undefined (reading 'httpServer')
```

**Comment by PeterAlfredLee** [comment]
I don't think the configure option `enforce: "pre"` would help - this option only make the `require.context` plugin transforms before vite's default plugin do.

```
[vite]: Rollup failed to resolve import "/src/Product/images/arrow_left.png" from "utilities/images-helper.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

Error: [vite]: Rollup failed to resolve import "/src/Product/images/arrow_left.png" from "utilities/images-helper.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

    at onRollupWarning (E:\root\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:41489:19)
    at onwarn (E:\root\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:41305:13)
    at Object.onwarn (E:\root\node_modules\rollup\dist\shared\rollup.js:23226:13)
    at ModuleLoader.handleResolveId (E:\root\node_modules\rollup\dist\shared\rollup.js:22510:26)
    at E:\root\node_modules\rollup\dist\shared\rollup.js:22471:26

TypeError: Cannot read properties of undefined (reading 'httpServer')
```
Through your original output, seems the plugin has already transformed the `require.context("../../../Product/images/", false, /^.+?\.png|jpg|svg|gif$/)` into urls of images `/src/Product/images/arrow_left.png`.

The error is weird - it reports that rollup cannot resolve the url as an import. It seems you only exported the require.context, and you didn't import anything. Could you provide some more detailed code on how are you using the exported images(I'm talking about the exported object `export const images = require.context("@Product/images/", false, /^.+?\.png|jpg|svg|gif$/)`)?

**Comment by PeterAlfredLee** [comment]
```javascript
import { getFullImageName, images } from "../utilities/images-helper";

const Logo: React.FC<LogoProps> = function Logo() {
  return <img src={images(getFullImageName("some_image"))} />;
};
```

I see. You are using `require.context` in jsx syntax. Seems we can't support such scenarios. Could you try it like this?
```javascript
import { getFullImageName, images } from "../utilities/images-helper";

const imageSrc = images(getFullImageName("some_image"));
const Logo: React.FC<LogoProps> = function Logo() {
  return <img src={imageSrc} />;
};
```
