### ISSUE TITLE
Transform failed with 1 error: Unterminated string literal

### ISSUE THREAD

**Issue by flora8984461** [originjs/vite-plugins#35]
### Versions

- originjs:  1.0.3
- node:  16.14.2

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tsxtjf?file=vite.config.js,main.js

Uncomment the part in `vite.config.js`

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

1. Open the reproduction link above
2. Uncomment the code part in `vite.config.js`
3. Re-run the project by `vite`, the error shows in console log and page does not load anything

### What is Expected?

Expect the transform to succeed and the project runs properly

### What is actually happening?

There is transform error:
```
 Internal server error: Transform failed with 1 error:<stdin>:2140:54: ERROR: Unterminated string literal
  Plugin: originjs:commonjs
  File: /home/projects/vitejs-vite-tsxtjf/packages/counter/dist/esm/index.js
      at failureErrorWithLog (/home/projects/vitejs-vite-tsxtjf/node_modules/esbuild/lib/main.js:1605:15)
      at eval (/home/projects/vitejs-vite-tsxtjf/node_modules/esbuild/lib/main.js:1394:29)
      at eval (/home/projects/vitejs-vite-tsxtjf/node_modules/esbuild/lib/main.js:666:9)
      at handleIncomingPacket (/home/projects/vitejs-vite-tsxtjf/node_modules/esbuild/lib/main.js:763:9)
      at Socket.readFromStdout (/home/projects/vitejs-vite-tsxtjf/node_modules/esbuild/lib/main.js:632:7)
      at EventEmitter.emit (https://vitejs-vite-tsxtjf.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:155573)
      at addChunk (https://vitejs-vite-tsxtjf.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:656476)
      at readableAddChunk (https://vitejs-vite-tsxtjf.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:656180)
      at Readable.push (https://vitejs-vite-tsxtjf.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:656864)
      at _0x461419.onStreamRead [as onread] (https://vitejs-vite-tsxtjf.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:783977)
```

Thank you so much for the plugin. Any help is really appreciated.

**Comment by Andrei-Ivanov98** [comment]
Have you managed to solve it after all?

**Comment by flora8984461** [comment]
Hi @Andrei-Ivanov98 thank you for check in. I re-examined our project and managed to remove "isomorphic-fetch" package. I didn't use the plugin and do not have this issue now.

**Comment by walmon** [comment]
I'm having this same issue, it doesn't even say in which line is the error to try and fix it. Any ideas if we can't just remove the package? My issue is happening with xlsx-populate
